lob/lob-typescript-sdk

.github/workflows/npm_publish.yml, README.md
=> fixed minor readme issue

.github/workflows/verify_automation_health.yml, scripts/verify_automation_health.sh
Add a script to github actions that fails the build whenever a non permitted user changes them. 
_Note: Currently that user is me, but we have plans of having a company wide automated user_
[JIRA-684](https://lobsters.atlassian.net/browse/DXP-684)
=> ci: add gh action and script for automation safety 

.github/workflows/monitor.yml, actions/monitoring/Dockerfile, actions/monitoring/action.yml, actions/monitoring/entrypoint.sh, actions/monitoring/slack_alerts.js, jest.config.js, package-lock.json, package.json
Added an action which runs all tests with an alert system. I set it to run twice every 24 hours, since Lob OpenAPI's monitoring system already runs every 30 minutes. We can figure out timings for both in the future.
[JIRA-657](https://lobsters.atlassian.net/browse/DXP-657)
=> Add slack notification

actions/monitoring/slack_alerts.js
Changed an incorrect link in the slack alerts workflow.
=> changed link to be correct

Migration.md
rephrased wording concerning newly supported endpoints for clarity
[JIRA-726](https://lobsters.atlassian.net/browse/DXP-726)
- [ x] Code runs without errors
- [x ] Tests pass with 100% coverage
=> rephrased wording concerning newly supported endpoints for clarity

scripts/verify_automation_health.sh
Change the author for the verification process
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-810)
=> ci: change the verification author

package-lock.json, package.json
=> modify_apiexception

__tests__/Postcards.unit.ts
This test evaluates not runtime operation
=> chore(test): remove a useless test

__tests__/PostcardsApi.spec.ts, __tests__/TemplatesApi.spec.ts
Please provide a brief summary of changes made and files affected
[JIRA-855](https://lobsters.atlassian.net/browse/DXP-855)
=> DXP-855: Postcards created in the staging environment are throwing errors

package-lock.json, package.json
The following dependencies are dev time of CI dependencies and should not be included in packages when a consumer installs:
- @actions/core
- @actions/github
- @octokit/core
- @semantic-release/npm
- @slack/web-api
- tslib
=> chore(package): move dev time and CI dependencies

.github/Contributing.md, .github/pull_request_template.md, Migration.md
Corrected a few typos in the GitHub template docs
=> chore(docs) revise wording on GH tempalte docs

Migration.md, models/lob-error.ts, package-lock.json
=> bulk_error_serialization

Migration.md, models/lob-error.ts, package-lock.json
=> add_co_error

models/letter-editable.ts
=> add-description-to-letter

.github/Contributing.md
Replicate Contributing change from PHP SDK to this SDK
=> doc(contributing) reword and correct

__tests__/ReverseGeocodeLookupsApi.unit.ts
Refactor a strange looking line of code for consistency
=> chore(test): revise expressions for revers geocode test

__tests__/IntlAutocompletions.unit.ts
Added unit tests for IntlAutocompletionsApi
=> chore(test) add unit tests for international autocompletions

models/letter-editable.ts
=> add_description_letter_create

models/check-editable.ts, models/letter-editable.ts
=> add_intl_verification_snippet

models/card.ts, models/check-editable.ts, models/letter-editable.ts, models/self-mailer.ts
Generation has been slow, so updating it
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-XXX)
=> fix: update generation

__tests__/IntlAutocompletionsApi.spec.ts
Added IntlAutocompletionsApi integration test file.
[JIRA-1033](https://lobsters.atlassian.net/browse/DXP-1033)
=> intlAutocompletionsApi integration test 

.github/workflows/release.yml
Adds the ability to release automatically through GHA based on the package json change
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-1025)
=> fix: add release for gha

README.md
Added legacy SDK link to README
[JIRA-1405](https://lobsters.atlassian.net/browse/DXP-1405)
=> docs: legacy SDK link

models/us-verification.ts
Please provide a brief summary of changes made and files affected
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-XXX)
=> fix: add valid address to verification response

package-lock.json
Please provide a brief summary of changes made and files affected
[JIRA-XXX](https://lobsters.atlassian.net/browse/DXP-XXX)
=> fix: bump json5 version for security

.github/workflows/forked_run_tests.yml, .github/workflows/npm_publish.yml, .github/workflows/release.yml, .github/workflows/run_tests.yml, package-lock.json, package.json
=> Uses node 20
